stages:
  - deploy

pages:
  stage: deploy
  image: python:3.12
  before_script:
    - python -m pip install make sphinx sphinx_rtd_theme
  script:
    - cd docs && make html
  after_script:
    - mv docs/build/html ./public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH